# Generated by Django 4.2.14 on 2024-07-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Объект строительства',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estimates.building')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='estimates.section', verbose_name='Родительская секция')),
            ],
            options={
                'verbose_name': 'Секция сметы',
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название расценки')),
                ('type', models.CharField(choices=[('work', 'Работа'), ('material', 'Материал')], max_length=8, verbose_name='Тип расценки')),
                ('count', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена за единицу')),
                ('section', models.ForeignKey(help_text='Расценка может принадлежать только той секции, у которой указан parent', on_delete=django.db.models.deletion.PROTECT, to='estimates.section')),
            ],
            options={
                'verbose_name': 'Расценка сметы',
            },
        ),
    ]
