# Generated by Django 4.2.14 on 2024-07-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Объект строительства', 'verbose_name_plural': 'Объекты строительства'},
        ),
        migrations.AlterModelOptions(
            name='expenditure',
            options={'verbose_name': 'Расценка сметы', 'verbose_name_plural': 'Расценка смет'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секция сметы', 'verbose_name_plural': 'Секция смет'},
        ),
        migrations.AlterField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estimates.section', verbose_name='Родительская секция'),
        ),
    ]
